version: '3.9'

services:
  hr-api:
    image: ${DOCKER_REGISTRY-}hrapi
    build:
      context: .
      dockerfile: src/Services/HR.API/Dockerfile

  hr-app:
    image: ${DOCKER_REGISTRY-}hrblazorwebassembly
    build:
      context: .
      dockerfile: src/Apps/HR.Blazor.WebAssembly/Dockerfile

